# toknow: by default, multiple jobs inside the same xx.yaml file run concurrently, unless explicitly dependencies is defined.
# Note:
# -  CI specific to dev branch
name: CI for dev branch

on:
  push:
    branches:
      - dev

jobs:
  install-go:
    uses: ./.github/workflows/ci_go-install.yaml

  checkout-code:
    needs: clone-code
    uses: ./.github/workflows/ci_code-checkout.yaml

  check-code:
    needs: clone-code
    uses: ./.github/workflows/ci_code-check.yaml

  install-code-dependencies:
    needs: clone-code
    uses: ./.github/workflows/ci_code-dep.yaml
