# toknow: by default, multiple jobs inside the same xx.yaml file run concurrently, unless explicitly dependencies is defined.
name: CI for dev branch

on:
  # manual trigger
  workflow_dispatch: 
  # trigger when push on branch
  push:
    branches:
      - dev

jobs:

  check-code:
    uses: abtransitionit/cicd-templates/.github/workflows/go-code-check.yaml@main
    with:
      go-version: '1.24'
