name: CI for main branch

on:
  push:
    branches:
      - main

jobs:
  install-go:
    uses: ./.github/workflows/ci_go-install.yaml

  code-check:
    needs: install-go
    uses: ./.github/workflows/ci_code-check.yaml

  code-test:
    needs: test-code
    uses: ./.github/workflows/ci_code-test.yaml
