# toknow: by default, multiple jobs inside the same xx.yaml file run concurrently, unless explicitly dependencies is defined.
# Note:
# -  CI specific to main branch
name: CI for main branch

on:
  push:
    branches:
      - main

jobs:
  install-go:
     uses: ./.github/workflows/ci_go-install.yaml
     with:
        go-version: '1.24'

  checkout-code:
    needs: install-go
    uses: ./.github/workflows/ci_code-checkout.yaml

  check-code:
    needs: checkout-code
    uses: ./.github/workflows/ci_code-check.yaml

  install-code-dependencies:
    needs: check-code
    uses: ./.github/workflows/ci_code-dep.yaml

  test-code:
    needs: install-code-dependencies
    uses: ./.github/workflows/ci_code-test.yaml
