# description: check/install the dependency of a Go project
# Note: 
#  - shared/common piece of code to 
#  - This workflow can be called from other workflows.
name: Install Go dependencies

on:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go dependencies
        run: |
          go mod tidy
