# description: check that the code and of a Go project
# Note: 
#  - shared/common piece of code to 
#  - This workflow can be called from other workflows.
name: Checkout code

on:
  workflow_call:

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
